CFLAGS = -I/zyp/eve/compiler/3rdParty

read: ReadTable.c
	gcc $(CFLAGS) ReadTable.c -o read
get: MakeGetChar.c
	gcc $(CFLAGS) MakeGetChar.c -o getchar
test: CheckTable.c
	gcc $(CFLAGS) CheckTable.c -o test

